apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iris-secret
  annotations:
    # Block the iris Deployment until the Secret materializes.
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: iris-secret
  dataFrom:
    - extract:
        key: secret/iris/config
