---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    proxmox:
      hosts:
        proxmox_host:
          ansible_host: 192.168.2.50

    vms:
      children:
        ubuntu_vms:
          hosts:
            immich:
              ansible_host: 192.168.2.202
              vm_id: 100
              domain: photos.halitdincer.com

        haos:
          hosts:
            home_assistant:
              ansible_host: 192.168.2.206
              vm_id: 103
              domain: ha.halitdincer.com
              # HAOS doesn't support SSH by default
              # Use HA REST API instead

        k3s:
          hosts:
            k3s:
              ansible_host: 192.168.2.216
              vm_id: 105
