---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    proxmox:
      hosts:
        proxmox_host:
          ansible_host: 10.10.10.1
          tailscale_hostname: proxmox

    vms:
      children:
        ubuntu_vms:
          hosts:
            immich:
              ansible_host: 10.10.10.100
              vm_id: 100
              domain: photos.halitdincer.com
            devbox:
              ansible_host: 10.10.10.106
              ansible_user: dincer
              ansible_become: true
              vm_id: 106
              domain: devbox.halitdincer.com

        haos:
          hosts:
            home_assistant:
              ansible_host: 10.10.10.103
              vm_id: 103
              domain: ha.halitdincer.com
              # HAOS doesn't support SSH by default
              # Use HA REST API instead

        k3s:
          hosts:
            k3s:
              ansible_host: 10.10.10.105
              vm_id: 105
