apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torontowebagency-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
