apiVersion: v1
kind: Service
metadata:
  name: torontowebagency
  labels:
    app: torontowebagency
spec:
  type: ClusterIP
  selector:
    app: torontowebagency
  ports:
    - name: http
      port: 3002
      targetPort: 3002
