apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "18.2.0"
    helm:
      values: |
        auth:
          username: coder
          database: coder
          existingSecret: coder-secret
          secretKeys:
            userPasswordKey: postgres-password
        primary:
          persistence:
            size: 10Gi
            storageClass: local-path
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: coder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
