apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.coder.com/v2
    chart: coder
    targetRevision: "2.30.1"
    helm:
      values: |
        coder:
          env:
            - name: CODER_ACCESS_URL
              value: "https://code.halitdincer.com"
            - name: CODER_POSTGRESQL_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-secret
                  key: CODER_POSTGRESQL_CONNECTION_URL
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: coder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
