apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-scout-data
  namespace: job-scout
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
