apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: job-scout-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: job-scout-secret
  dataFrom:
    - extract:
        key: secret/job-scout/config
