apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-scout
resources:
  - ../../base
images:
  - name: ghcr.io/halitdincer/job-scout
    newTag: latest
    newName: ghcr.io/halitdincer/job-scout
    digest: sha256:a3bcc49f8e5a771cabfd90b8cafc800b2c92d60c2b088632238f26a6ab130c0e
