apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-scout
resources:
  - ../../base
images:
  - name: ghcr.io/halitdincer/job-scout
    newTag: latest
    newName: ghcr.io/halitdincer/job-scout
    digest: sha256:50bcfa6e61d296b3c0a98353913113af7df54c6b4422d24a552b8f4dae530a78
