apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-scout
resources:
  - ../../base
images:
  - name: ghcr.io/halitdincer/job-scout
    newTag: latest
    newName: ghcr.io/halitdincer/job-scout
    digest: sha256:d56f1196c4ae2c8a268fa702e2d423bc15a441513f358413640b79667406ec09
