apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-secret
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: home-assistant-secret
  dataFrom:
    - extract:
        key: secret/coder/home-assistant
