---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: code-server-secret
  namespace: default
spec:
  encryptedData:
    password: AgAyWloXCxr0LurpfKjSNS2PN6Ny/XYVua3LJk3mXX383McdM1BGzwNky4JdLoAFfn/5bP84JMsdxC78Ej7r+H+dLyBlBIEP78j20Qw/v8DmBPenihCIFKnJH2GOZvSOW/GRO9Dh0VV1QwvsjW+wIBHqpCUNsreDCQm69U7w/6MD5kamGcRVRrbiJmCqdB9pOU2eHTu5m1EoJ5jxOoi4sMOXFAtkttkMK3HDlVJeuhEFnie9PsTBlHGJ94QCkeJAk7DfP4LVAjXdTzoREwykM+q9e5vEzPcu/6cE4/DGnjTE60xYgW/Y84XzpPhXu2YLYCiVT5BjLTwbjBghcQ1ChiGjeXw5udSCbYEn7kzG9CY+cAcnRBdpTBP0uxK47DMDyDATLynPlw3OmyKuISAw29peAeCP3oMm3K3DPsfiiwwAv3KcspxB7Jwp/sxfNjVmtbdvA/0K1OfOpP3NO9/JcpuRLvROhtI0ZsYbrpmPRkNM1c12Z8OXlWogmDptsILPv2FcQ4vyZ2Ahfiwcgz85Za8Io3dOzWb5kppUVA4UHDSWzvNJy5RW1B2v2kjroGKLYRHhIBJYhYaySo5w78lcn4t+6JsIYE4/Hev6s6TQb4gm0up5Oyqzd0Cu2166zm3hh1wvM++M92ubhD8B/bJ8oH0tkRRSUejXOSSUblmPoMZvnQFln24d0enRjEr9Tb27/kag/En0uaIXtQ==
  template:
    metadata:
      name: code-server-secret
      namespace: default
