apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeserver-iac-secret
  namespace: coder
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homeserver-iac-secret
  dataFrom:
    - extract:
        key: secret/coder/homeserver-iac
