apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: code-server-secret
  dataFrom:
    - extract:
        key: secret/code-server/config
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: secret/job-scout/config
        property: ANTHROPIC_API_KEY
