apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-secret
  namespace: coder
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: coder-secret
  dataFrom:
    - extract:
        key: secret/coder/config
