apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/halitdincer/bid-on-time
    newName: ghcr.io/halitdincer/bid-on-time
    newTag: latest
    digest: sha256:84bf09b9dd38da544bbca4925d22b39e6be6587e85a95ae05cac9188de01d56e
